### PR TITLE
add option for contig blocks

### LINKED ISSUE #63: Feature request: support IPv6 pools with Amazon-owned CIDRs
Currently the following doesn't work because `top_cidr` is required, but conflicts with netmask_length:

```terraform
module "this6" {
  source  = "registry.terraform.io/aws-ia/ipam/aws"
  version = "~> 2.0.0"

  top_netmask_length = 48

  # scope ID created by another instantiation of this module for an IPv4 pool
  ipam_scope_id   = module.this.ipam_info.public_default_scope_id
  ipam_scope_type = "public"

  create_ipam = false

  top_name       = "global ipam 6"
  address_family = "ipv6"

  pool_configurations = {
    corporate-eu6 = {
      locale = "eu-central-1"
      aws_service = "ec2"

      sub_pools = {
        sandbox = {
          name                 = "sandbox-dev-6"
          netmask_length       = 52
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by drewmullen**
closes #63

### CODE REVIEW

**Comment by lenasappvia** [comment]
Hello! Thank you for this feature, this is exactly what I need for the AWS issued IPV6. @andrew-glenn / @tlindsay42 is there any chance this could be reviewed? I appreciate your time!

**Review by pablo19sc — APPROVED** [review]
All good

**Comment by lenasappvia** [comment]
Awesome to see this approved! 🎉 Any idea when this will be merged in? @andrew-glenn / @pablo19sc / @tlindsay42 ? 😸

**Comment by pablo19sc** [comment]
Hi! Let me work on this. I'd try to have it merged worst case beginning of next week - we have some PRs also in other modules, but I'm taking these two weeks to clean the queue.

**Comment by lenasappvia** [comment]
Hi @pablo19sc , thank you for looking into this and prompt reply, much appreciated! 👯 🍰

**Pull request merged**
